### ISSUE TITLE
Instructions for running elaborate example

### ISSUE THREAD

**Issue by cliffckerr** [gyyang/neurogym#1]
Would it be possible to add instructions on how to get the environment recognized by `baselines`? Following the instructions as-is gives:
```
python run.py --alg=a2c --env=RDM-v0 --network=lstm --nsteps=20 --nlstm=64 --stimEv=0.5 --pass_reward=True --pass_action=True --timing 200 200 300 400 200

Logging to /tmp/openai-2019-07-17-12-35-19-692762
Traceback (most recent call last):
  File "run.py", line 250, in <module>
    main(sys.argv)
  File "run.py", line 216, in main
    model, env = train(args, extra_args)
  File "run.py", line 54, in train
    env_type, env_id = get_env_type(args)
  File "run.py", line 143, in get_env_type
    assert env_type is not None, 'env_id {} is not recognized in env types'.format(env_id, _game_envs.keys())
AssertionError: env_id RDM-v0 is not recognized in env types
```

The `baselines` documentation also does not obviously suggest how to register external environments, although I didn't spend too much time investigating...

**Comment by manuelmolano** [comment]
Hi! Did the test_new.py example work? Here is a simpler code that should make one step in the RDM task:
```
import gym
from neurogym.ops import task_registrations
#TASK
task = 'RDM-v0'
#register task on gym
task_registrations.register_neuroTask(task)
#initialize task
env = gym.make(task, **{'dt': dt})
#randomly sample an action
action = env.action_space.sample()
#pass action to environment and get: 
#1. A new observation.
#2. Reward.
#3. Done flag.
#4. Extra information.
obs, rew, done, info = env.step(action)
```
For the Baselines toolbox, you should modify a bit the run.py code to register the task using the task_registrations.register_neuroTask() function.

Let me know!

**Comment by manuelmolano** [comment]
hi! we have modified the import code so all tasks are registered when neuroGym is imported. 
Also, we have added a colab notebook ([neuroGym_colab.ipynb](https://github.com/gyyang/neurogym/blob/master/neuroGym_colab.ipynb)) that shows how to use the toolbox.

**Comment by cliffckerr** [comment]
Sorry, I didn't get a chance to test this, but trust it works :)
