### ISSUE TITLE
ngym env print too many info by default

### ISSUE THREAD

**Issue by gyyang** [gyyang/neurogym#4]
The default ngym env print many things at every reset. And there's no way to suppress this from the user's end.

def reset(self):
        """
        restarts the experiment with the same parameters
        """
        if self.num_tr > 1:
            print(self.__class__.__name__)
            print('percentage of trials performed: ' +
                  str(100*self.num_tr_perf/self.num_tr_exp))
            print('mean performance: ' + str(self.perf))

        self.perf = 0
        self.num_tr_perf = 0
        self.num_tr = 1
        self.t = 0

        self.trial = self._new_trial()
        obs, _, _, _ = self.step(self.action_space.sample())
        return obs

**Comment by manuelmolano** [comment]
I removed those prints
