### ISSUE TITLE
issue with RandomState

### ISSUE THREAD

**Issue by manuelmolano** [gyyang/neurogym#8]
Version 3.7.4

```
import numpy as np
 a = np.random.RandomState(0)
 a.random()

0.5488135039273248
```

version 3.6.5

```
import numpy as np
 a = np.random.RandomState(0)
 a.random()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'mtrand.RandomState' object has no attribute 'random'
```

**Comment by gyyang** [comment]
I can't reproduce this issue. It's more likely a numpy version problem, rather than a python version problem. What's the numpy version used?

**Comment by manuelmolano** [comment]
The numpy version that gives the error is 1.16.0.

**Comment by gyyang** [comment]
Fixed by replacing rng.random() with rng.rand(). [https://github.com/gyyang/neurogym/commit/e5a8daabee8d04e6da5804cb8acdd535b237b698](url)
